[package]
name = "hasher"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
md5 = "0.7"
blake2 = "0.10"
walkdir = "2.4"
rayon = "1.10"
clap = { version = "4.4", features = ["derive"] }
